apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    editable: false
    jsonData:
      client: standalone
