apiVersion: v1
kind: ConfigMap
metadata:
  name: robo-trader-config
  namespace: trading
data:
  environment: "production"
  log_level: "INFO"
  ibkr_host: "ibkr-gateway.trading.svc.cluster.local"
  ibkr_port: "7496"
  
  production.json: |
    {
      "trading_limits": {
        "max_position_size": 10000,
        "max_daily_loss": 5000,
        "max_daily_trades": 100,
        "max_open_positions": 10,
        "max_leverage": 1.0,
        "allowed_symbols": [
          "AAPL", "GOOGL", "MSFT", "AMZN", "META",
          "NVDA", "TSLA", "JPM", "V", "JNJ",
          "WMT", "PG", "UNH", "HD", "MA",
          "DIS", "BAC", "XOM", "CVX", "ABBV"
        ],
        "blocked_symbols": [],
        "trading_hours_start": "09:30",
        "trading_hours_end": "16:00",
        "enable_short_selling": false,
        "require_stop_loss": true,
        "max_slippage_percent": 0.5
      },
      "alerting": {
        "enable_alerts": true,
        "alert_channels": ["slack", "log"],
        "slack_channel": "#trading-alerts",
        "pnl_alert_threshold": 1000,
        "drawdown_alert_threshold": 0.05,
        "error_rate_threshold": 0.1,
        "latency_alert_ms": 1000
      },
      "feature_flags": {
        "enable_paper_trading": false,
        "enable_live_trading": true,
        "enable_ml_predictions": false,
        "enable_news_sentiment": false,
        "enable_options_trading": false,
        "enable_crypto_trading": false,
        "enable_international_markets": false,
        "use_advanced_risk_models": true,
        "log_all_orders": true,
        "dry_run_mode": false,
        "maintenance_mode": false
      },
      "ibkr": {
        "client_id": 1,
        "enable_delayed_data": false,
        "connection_timeout": 30,
        "request_timeout": 10,
        "max_retry_attempts": 3
      },
      "database": {
        "db_type": "postgresql",
        "connection_pool_size": 10,
        "enable_ssl": true
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robo-trader-monitoring
  namespace: trading
data:
  prometheus-rules.yaml: |
    groups:
    - name: robo_trader
      interval: 30s
      rules:
      - alert: TradingSystemDown
        expr: up{job="robo-trader"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Trading system is down"
          description: "Trading system has been down for more than 2 minutes"
      
      - alert: HighDailyLoss
        expr: trading_daily_pnl < -1000
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High daily loss detected"
          description: "Daily P&L is {{ $value }}"
      
      - alert: IBKRDisconnected
        expr: component_trading_up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "IBKR connection lost"
          description: "Trading system disconnected from IBKR for 5+ minutes"
      
      - alert: HighErrorRate
        expr: rate(trading_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors/sec"
      
      - alert: HighMemoryUsage
        expr: system_memory_percent > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"