"""Dormant order-safety core.

Importing this package performs no filesystem, database, broker, configuration,
or runtime work.  Runtime integration is intentionally deferred to a later PR.
"""

from .journal import (
    IdempotencyConflict,
    JournalError,
    JournalIntegrityError,
    ReservationConflict,
    SafetyJournal,
    StateTransitionError,
)
from .models import (
    MODEL_VERSION,
    SAFETY_MAX_EVIDENCE_AGE_SECONDS,
    DecisionOutcome,
    EvidenceStatus,
    ExposureEvidence,
    GateContext,
    JournalEvent,
    JournalEventType,
    OrderIntent,
    OrderSide,
    OrderType,
    PortfolioAllocationEvidence,
    ReconciliationEvidence,
    ReconciliationStatus,
    ReplayReservation,
    ReplayState,
    Reservation,
    RiskEffect,
    SafetyDecision,
    SubmissionClaim,
    SubmissionDescriptor,
    SubmissionPermit,
    TerminalOrderStatus,
    TimeInForce,
    TransportState,
    ValidationError,
    canonical_json,
    decimal_to_fixed,
)
from .policy import ReduceOnlyPolicy, evaluate_reduce_only

__all__ = [
    "MODEL_VERSION",
    "SAFETY_MAX_EVIDENCE_AGE_SECONDS",
    "DecisionOutcome",
    "EvidenceStatus",
    "ExposureEvidence",
    "GateContext",
    "IdempotencyConflict",
    "JournalError",
    "JournalEvent",
    "JournalEventType",
    "JournalIntegrityError",
    "OrderIntent",
    "OrderSide",
    "OrderType",
    "PortfolioAllocationEvidence",
    "ReconciliationEvidence",
    "ReconciliationStatus",
    "ReduceOnlyPolicy",
    "ReplayReservation",
    "ReplayState",
    "Reservation",
    "ReservationConflict",
    "RiskEffect",
    "SafetyDecision",
    "SafetyJournal",
    "StateTransitionError",
    "SubmissionClaim",
    "SubmissionDescriptor",
    "SubmissionPermit",
    "TerminalOrderStatus",
    "TimeInForce",
    "TransportState",
    "ValidationError",
    "canonical_json",
    "decimal_to_fixed",
    "evaluate_reduce_only",
]
